server:
  port: 5000

mock-api:
  protocol: http
  domain: localhost
  port: 3001
  resource: product

resilience4j:
  circuitbreaker:
    instances:
      MockService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 3
        automatic-transition-from-open-to-half-open-enabled: true